
server:
  port: 8081
  servlet:
    contextPath: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG
  org.springframework.security.web.csrf.CsrfFilter: DEBUG

spring:
  datasource:
    url: 'jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:calculador}'
    username: ${DATABASE_USER:bemindersuser}
    password: ${DATABASE_PASSWORD:beminders}
  jpa:
    hibernate:
      # cria as tabelas no banco automaticamente
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id : ${GOOGLE_CLIENT_ID:578972637586-uoude02731bghftaun7ktppu2s5ctebt.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: oauth2-calculador
            user-name-attribute: email